spring.application.name=AI
dashscope.api.key=sk-df1805ed55954c979938fbedf638f53a

spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=2787901285@qq.com
spring.mail.password=mdrdosvfrwgsdgbb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.task.scheduling.enabled=true
spring.mail.properties.mail.smtp.from=2787901285@qq.com
